on: push
name: Push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test
    - name: git-config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    - name: build
      run: |
        npm run build
        git add dist/*
        git commit -m "build (ci)"
        git push